### ISSUE TITLE
Update links in the frontend roadmaps

### ISSUE THREAD

**Issue by Shashmit** [commclassroom/roadmaps#109]
In the Frontend Roadmap there is this link for  the **CSS -> Resource 2** it is redirecting to the HTML learning page of Codecademy. It should redirect it to the CSS learning page.

**Comment by kaiwalyakoparkar** [comment]
Thanks for reporting. We will look into it

**Comment by Shashmit** [comment]
Ohk

**Comment by kaiwalyakoparkar** [comment]
Thank you so much for reporting this @Shashmit this has been resolved. The site will reflect changes after some time
