### ISSUE TITLE
[feat] Issue and PR template

### ISSUE THREAD

**Issue by octonawish-akcodes** [commclassroom/roadmaps#11]
It would be really easy for new contributors to add things at the relevant positions while raising an issue or PR, so adding of both templates can be beneficial.

**Comment by kaiwalyakoparkar** [comment]
@octonawish-akcodes thank you so much for this suggestion.

**Comment by octonawish-akcodes** [comment]
I can work on this @kaiwalyakoparkar

**Comment by kaiwalyakoparkar** [comment]
@octonawish-akcodes assigned to you
