### ISSUE TITLE
Adding one more operating system resource in the Devops roadmap

### ISSUE THREAD

**Issue by SaadAnsari17** [commclassroom/roadmaps#115]
I am learning OS from this course and it's by far the best course I have come across explaining every nuance and making it easy to understand.
https://youtube.com/playlist?list=PLBlnK6fEyqRiVhbXDGLXDk_OQAeuVcp2O
Can I make a pull request adding this resource to the roadmap?

**Comment by kaiwalyakoparkar** [comment]
@SaadAnsari17 thank you for the issue but this will be worked on by the team

**Comment by kaiwalyakoparkar** [comment]
@SaadAnsari17 this has been done. Thank you so much for recommending it. This has been added as "Resource 6"

**Comment by SaadAnsari17** [comment]
My Pleasure :)

**Comment by SaadAnsari17** [comment]
![image](https://user-images.githubusercontent.com/94478736/185587730-9ff3422a-3bee-44aa-9b32-884936089ff1.png)
Kindly please add an arrow to that resource.
