### ISSUE TITLE
Wrong link for resources

### ISSUE THREAD

**Issue by hamees-sayed** [commclassroom/roadmaps#12]
https://www.commclassroom.org/devops-roadmap
Here, the link for `Chef, Puppet, Ansible Course` and `Ansible Docs` under `Configuration Management` needs to be corrected

**Comment by kelvinparmar** [comment]
Hey I would like to contribute on it

**Comment by kelvinparmar** [comment]
Please give the instruction for it

**Comment by kaiwalyakoparkar** [comment]
Hey @hamees-sayed thanks for the report, the changes will be reflected on website soon. Keeping this issue open util it's live

**Comment by kaiwalyakoparkar** [comment]
@kelvinparmar you can check out #11 and #2 for contribution

**Comment by kaiwalyakoparkar** [comment]
@hamees-sayed this has been resolved now. Thanks for reporting

**Comment by shiv324** [comment]
I am new here . I want to know what to do to contribute?

**Comment by kaiwalyakoparkar** [comment]
@shiv324 please check out issues section and `good-first-issues` tag -> comment on that issue showing your interest -> Get it assigned -> work on the issue -> submit pr 🎉 
You can also create new issues if you have any suggestions or add them to the Discussions tab (right side of pull request tab) Let us know if you need any help :)
