### ISSUE TITLE
📦 NEW : Blockchain ---> Job-Boards

### ISSUE THREAD

**Issue by ishvinder-singh** [commclassroom/roadmaps#123]
Hi, I wanted to add a new job hunting website in the /Blockchain ---> Job-Boards folder. Can I create a PR ?
Thanks :)

**Comment by cosmicqbit** [comment]
Just do it already man. The PR will be reviewed regardless.

**Comment by kaiwalyakoparkar** [comment]
Hey @ishvinder-singh as @cosmicqbit you can go ahead with the PR. We make sure to review every PR
