### ISSUE TITLE
[Bug] <description>

### ISSUE THREAD

**Issue by shiv324** [commclassroom/roadmaps#129]
### Description

There is a bug in Android and blockchain roadmap. When you open it , the page gets stuck and you cant do anything , cant even zoom in it.

**Comment by cosmicqbit** [comment]
The report is insufficient. Consider mentioning the type of device & browser you are using, even better include screen shots with reference. 

On the same note, I just visited the aforementioned roadmaps from PC using Firefox and both of 'em are working like charm. 

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/75565639/185736416-b5c6668b-c5ca-45b3-9e64-14210c349dd1.png">

<img width="927" alt="image" src="https://user-images.githubusercontent.com/75565639/185736425-4fdd8285-ffb6-4bd6-b928-c8827523cd13.png">

**Comment by kaiwalyakoparkar** [comment]
Thank you for the report @shiv324 and @cosmicqbit. This is a known issue. Please use chrome browser
