### ISSUE TITLE
Discord Invite invalid ( Sema and Hack Club Hakerabad Communities )

### ISSUE THREAD

**Issue by Mohand2** [commclassroom/roadmaps#13]
Discord Invite invalid ( Sema and Hack Club Hakerabad Communities )

**Comment by kaiwalyakoparkar** [comment]
Thanks on reporting @Mohand2. I will check and inform you with updated once

**Comment by kaiwalyakoparkar** [comment]
@Mohand2 this has been fixed. Thank you so much for reporting :)
