### ISSUE TITLE
bug/some unwanted resources added in frontend roadmap

### ISSUE THREAD

**Issue by rahul09999** [commclassroom/roadmaps#140]
### Description

In frontend roadmap,in framework section it redirect to some meta/apple careers portal instead of resources.Attaching pic with tick mark on it having that problem

### Screenshots

![Screenshot (16)](https://user-images.githubusercontent.com/92937491/185777127-aa9c645d-6b2e-47d3-b772-5338d80fbbc0.png)

**Comment by KlausMikhaelson** [comment]
Hello @rahul09999 even I noticed this bug and would like to work on it if no-one has started yet

**Comment by kaiwalyakoparkar** [comment]
Thank you so much for the report @rahul09999 and thank you for showing interest @KlausMikhaelson but this issue will be worked on by the team

**Comment by kaiwalyakoparkar** [comment]
Thank you for the report @rahul09999. This issue has been resolved
