### ISSUE TITLE
[Wrong Link In Open Source Roadmap] <The Git Documentation link in the open source roadmap is not linking to the git documentation>

### ISSUE THREAD

**Issue by SaarthakMaini** [commclassroom/roadmaps#141]
### Description

The Git Documentation link in the open source roadmap is not linked to the git documentation. Instead, it is linked to a video that has already been mentioned in the roadmap above.

Please refer to the screenshot given below

Solution:

Change the link of "Git Documentation"  from 

https://www.youtube.com/watch?v=yzeVMecydCE

to 

https://git-scm.com/doc

OR 

https://git-scm.com/book/en/v2

### Screenshots

![image](https://user-images.githubusercontent.com/94912101/185787507-d26a4634-91e7-467c-b01a-afa32888ff36.png)

**Comment by kaiwalyakoparkar** [comment]
Thank you so much for reporting @SaarthakMaini

**Comment by kaiwalyakoparkar** [comment]
Thank you so much for the report. This issue has been fixed
