### ISSUE TITLE
[Wrong link in Blockchain Roadmap] 

### ISSUE THREAD

**Issue by mullaivanaraj** [commclassroom/roadmaps#142]
### Description

The link "SOLIDITY DOCS" in the Blockchain roadmap is not linked to the Solidity documentation. Instead, it is linked to a video (Rick Astley - Never Gonna Give You Up (Official Music Video)).

### Screenshots

Please find the attached screenshot below!
![github solidity docs issue](https://user-images.githubusercontent.com/47219765/185800268-9f07964a-b50d-49d6-a714-18bffcd9191d.jpg)

### Additional information

Solution:

Change the corresponding URL to "https://docs.soliditylang.org/en/v0.8.16/"

**Comment by cosmicqbit** [comment]
Dude prefer to use brief title for the issue, like "Wrong link in Blockchain Roadmap"

**Comment by mullaivanaraj** [comment]
Sure, will change it. Thanks!
