### ISSUE TITLE
I want to add a slack community for both frontend and backend

### ISSUE THREAD

**Issue by Shubhcs01** [commclassroom/roadmaps#143]
### Which field of community (DevOps/Opensource/Web/Web3/Android/Devrel) you want to add, drop the links?

HackerEarth Slack - https://join.slack.com/t/hackerearthdevs/shared_invite/zt-1eg0jqmlz-YdvV_Ym1Xby6LJFcqydXIQ
Frontend Mentor - https://join.slack.com/t/frontendmentor/shared_invite/zt-1enudath0-ozW32EpT2Ixn~5JTG0dCog

**Comment by cosmicqbit** [comment]
@Shubhcs01 Request a PR instead, which gets reviewed anyway & mark this issue **closed** already.

**Comment by Shubhcs01** [comment]
okay
