### ISSUE TITLE
[[Bug] Displaying resource link in some roadmap also traget_blank which will open it on new page]

### ISSUE THREAD

**Issue by deep1910** [commclassroom/roadmaps#145]
### Description

This occurs only in some roadmap such as 

BLOCKCHAIN 
DEVOPS
ANDROID DEVELOPMENT 

Kindly confirm if displaying link is a feature or bug in these roadmaps or it will be updated

Displaying link can be the feature but displaying  target_blank what;s the point?

kindly coney if I am wrong!

### Screenshots

![Uploading Screenshot 2022-08-20 234927.png…]()
![Screenshot 2022-08-22 154952](https://user-images.githubusercontent.com/92329233/185898828-2b141417-e6a3-492a-b9f8-2e995b060de6.png)

**Comment by kaiwalyakoparkar** [comment]
@deep1910 thank you for the report but we are unable to find any option on the platform that let's us alter this. We will keep an eye if we come across any good solution. I will be closing this issue as of now
