### ISSUE TITLE
Non functional link in the footer of the website

### ISSUE THREAD

**Issue by Abhiram-Gullapalli** [commclassroom/roadmaps#148]
### Description

The link to the "team" under the organization section at the footer of the website is non-responsive.

**Comment by Abhiram-Gullapalli** [comment]
I would be personally working on this

**Comment by kaiwalyakoparkar** [comment]
@Abhiram-Gullapalli can you please add a screenshot or gif of the issue?

**Comment by Abhiram-Gullapalli** [comment]
I hope you understood what I'm trying to convey, the video isn't that clear but hope you got it @kaiwalyakoparkar

**Comment by kaiwalyakoparkar** [comment]
@Abhiram-Gullapalli Thank you so much for reporting. We will take a look into the issue

**Comment by Sharptooth14** [comment]
Can you please mention the file location of the bug???
