### ISSUE TITLE
Adding `kubescape Discord` to `DevOps/Communities` folder

### ISSUE THREAD

**Issue by Omkar0114** [commclassroom/roadmaps#149]
### Which field of community (DevOps/Opensource/Web/Web3/Android/Devrel) you want to add, drop the links?

DevOps community
kubescape Discord link here: https://discord.com/invite/WKZRaCtBxN

**Comment by Omkar0114** [comment]
Hey @kaiwalyakoparkar ,
Can you assign it to me? :)

**Comment by siddhant-khisty** [comment]
Hey @Omkar0114, feel free to make a PR for this, and link this issue as well 😄

**Comment by Omkar0114** [comment]
Yep
