### ISSUE TITLE
Typo error in "Blockchain Roadmap"

### ISSUE THREAD

**Issue by mullaivanaraj** [commclassroom/roadmaps#150]
### Description

Proof of Stack is present instead of Proof-of-Stake (PoS).

### Screenshots

![github proof of stake](https://user-images.githubusercontent.com/47219765/185993549-07c61974-f844-43df-87e1-89a9f5c0b63a.jpg)

### Additional information

Change "Proof of Stack" to Proof-of-Stake (PoS).

**Comment by siddhant-khisty** [comment]
#147  mentions the same issue. Working on it 😃
