### ISSUE TITLE
Feature: Add roadmap to Private Blockchain

### ISSUE THREAD

**Issue by shoaibshebi** [commclassroom/roadmaps#152]
### Description

I had a look at the blockchain road map, it was awesome. But There was a very major thing that was missing, Private Blockchain.
All the stuff that was mentioned is about Public blockchain, so that's why i designed the roadmap for  public blockchain.

### Screenshots

![ss](https://user-images.githubusercontent.com/47749364/186096648-9c103c8f-b922-48c3-9cec-b40179b6270f.png)

**Comment by shoaibshebi** [comment]
@siddhant-khisty 
I'm not able to find it on the website under blockchain section
can you please send me the link?

**Comment by siddhant-khisty** [comment]
cc @kaiwalyakoparkar
