### ISSUE TITLE
Adding OSS project to `Devops/contribute` folder

### ISSUE THREAD

**Issue by Pranav-Shinde11** [commclassroom/roadmaps#158]
### Which field of community (DevOps/Opensource/Web/Web3/Android/Devrel) you want to add, drop the links?

I want to add `kubescape` project 
link here:  https://github.com/kubescape/kubescape

**Comment by Pranav-Shinde11** [comment]
Hi @kaiwalyakoparkar,
I want to work on this issue can you assign it to me? :)

**Comment by kaiwalyakoparkar** [comment]
@Pranav-Shinde11 I have already assigned it to you
