### ISSUE TITLE
Add 'Namaste Javascript' playlist to Backend Development roadmap

### ISSUE THREAD

**Issue by servesh-chaturvedi** [commclassroom/roadmaps#161]
##  Description
This is a highly popular theoretical javascript playlist which goes in-depth about core JS concepts. The videos are short and engaging and clarify some basic misconceptions and will help for interviews too.

### Playlist link:
[Namaste Javascript](https://youtube.com/playlist?list=PLlasXeu85E9cQ32gLCvAvr9vNaUccPVNP) by Akshay Saini

**Comment by siddhant-khisty** [comment]
stale for more than 30 days
