### ISSUE TITLE
Same resource repeated in CSS tutorials.

### ISSUE THREAD

**Issue by SaadAnsari17** [commclassroom/roadmaps#171]
### Description

The same link is provided in Resource 1 and Resource 2 in CSS tutorials in the front-end roadmap.

**Comment by kaiwalyakoparkar** [comment]
Thank you for the report @SaadAnsari17 this has been resolved now

**Comment by SaadAnsari17** [comment]
> Thank you for the report @SaadAnsari17 this has been resolved now

My pleasure :)
