### ISSUE TITLE
[Missing Arrow] <There is no arrow pointing towards "Resource 2" from "Front End Projects" section>

### ISSUE THREAD

**Issue by SaarthakMaini** [commclassroom/roadmaps#172]
### Description

There is no arrow pointing towards "Resource 2" from "Front End Projects" section

The same is given in the screenshot attached below

### Screenshots

![image](https://user-images.githubusercontent.com/94912101/187079194-1c0279fb-8f2e-4868-8c94-11902ce15a36.png)

**Comment by kaiwalyakoparkar** [comment]
Thank you so much for the report @SaarthakMaini this has been resolved now
