### ISSUE TITLE
Wrong Link added under Android Roadmap -> Introduction to Kotlin -> Kotlin in 12 minutes 

### ISSUE THREAD

**Issue by AmanGit010** [commclassroom/roadmaps#173]
Current video link for Kotlin in 12 minutes takes us to Android Studio installation video by Rahul Pandey -> (https://www.youtube.com/watch?v=4M0hNugPJV8&ab_channel=RahulPandey)

Correct video link for Kotlin in 12 minutes by Rahul Pandey -> (https://www.youtube.com/watch?v=iYrgWO2oibY&t=11s&ab_channel=RahulPandey)

Link to Android Roadmap -> (https://www.commclassroom.org/android-roadmap)

**Comment by SaptarshiSarkar12** [comment]
Yes @AmanGit010 is right.
@kaiwalyakoparkar Please sort out the issue as soon as possible to prevent confusions.

**Comment by SaptarshiSarkar12** [comment]
@kaiwalyakoparkar Please add the <code>**bug**</code> label

**Comment by siddhant-khisty** [comment]
@kaiwalyakoparkar  can you please make a label called `re-embed required`?

**Comment by kaiwalyakoparkar** [comment]
@siddhant-khisty done

**Comment by kaiwalyakoparkar** [comment]
@AmanGit010 thank you so much for the report. This has been resolved now

**Comment by AmanGit010** [comment]
Welcome buddy 😊
