### ISSUE TITLE
Open source project by Language

### ISSUE THREAD

**Issue by Praxkv1** [commclassroom/roadmaps#176]
### Description

Can we add a category called Languages and have an option to search project by language. Today if i am infested in python projects i need to open each and every project listed here and see what is the language that project is using which i feel is an overhead.

![image](https://user-images.githubusercontent.com/6167307/187967880-9822a6f9-795a-48e8-85c4-db4ed59169b9.png)

**Comment by siddhant-khisty** [comment]
@Praxkv1 This sounds like a good idea. However many projects use multiple languages. Instead, we could add what tech stack it uses in front of the project. How does that sound?

**Comment by Susmita-Dey** [comment]
@siddhant-khisty Sounds good.

**Comment by Praxkv1** [comment]
> @Praxkv1 This sounds like a good idea. However many projects use multiple languages. Instead, we could add what tech stack it uses in front of the project. How does that sound?

@siddhant-khisty @Susmita-Dey 
Yes this is a good catch. Is there a way we can add tags to the project? if so we can add programing language as a tag along with the percentage of that specific programing language being used in that project. 

For example if 
**Project1** is built using 60% `python`and 40% `Typescript`
**Project2** is built using 40% `python` and 60% `Typescript`

Then when some one search for project of type `Python` then you show them **Project1** first then **Project2** (result sorted by % of language used in descending order)

**Comment by kaiwalyakoparkar** [comment]
@Praxkv1 percent won't be a good idea as there is no accurate way I know which could derive the percent of language used in the project. Additionally, GitHub doesn't provide such feature (If you know about any please let us know). If you click on the project it will be redirected to the project repo where you are most likely to find languages used. Please feel free to open new issue if you come across any solution 😄
