### ISSUE TITLE
Want to add a new github repo to contribute 

### ISSUE THREAD

**Issue by asifurrahaman754** [commclassroom/roadmaps#181]
### Description

I want to add a new GitHub repository to contribute. It is a frontend-interview-handbook. Here one can learn about frontend interviews, how to create a good resume, which questions to prepare etc.

**Comment by siddhant-khisty** [comment]
Hey, we want to link GitHub repo's where you can work on the specified domain. This still sounds like a good resource for beginners with the front-end. I think we can make a folder called `useful resources` and have it there.
cc @kaiwalyakoparkar
