### ISSUE TITLE
[React JS/JavaScript Engineer - Andela] not found in the frontend job board

### ISSUE THREAD

**Issue by asifurrahaman754** [commclassroom/roadmaps#183]
### Description

The [React JS/JavaScript Engineer - Andela] is not found on the frontend job board. I think the page URL is changed or something, it shows 404. Should I remove it or change it to the correct url?

**Comment by siddhant-khisty** [comment]
Hey @asifurrahaman754, I think this was pointing to a job posting rather than a job board. Feel free to make a PR to remove it. If you see any other ones like this which are pointing to job postings, please make PRs to either remove them or point to job boards on that website

**Comment by asifurrahaman754** [comment]
got it

**Comment by asifurrahaman754** [comment]
@siddhant-khisty I made a pr, will u check it, please? 
link: https://github.com/commclassroom/roadmaps/pull/184
