### ISSUE TITLE
[Bug] Missing Links in FullStack Roadmap

### ISSUE THREAD

**Issue by rushikeshsuryawanshi** [commclassroom/roadmaps#186]
### Description

The First 2 steps in the Full Stack Roadmap i.e.

1. Get Started with Frontend
2. Get Started with Backend

These 2 steps are missing links to the roadmaps.

Yes, users can navigate back and forth, and get to those roadmaps. 
But this could improve user experience.

### Screenshots

![image](https://user-images.githubusercontent.com/55173065/191720677-1eb988c2-19c9-4c05-b06e-27324a980781.png)

**Comment by siddhant-khisty** [comment]
Hey, thanks for the idea. This will be handled by our internal team :)
