### ISSUE TITLE
Update Readme for Hacktoberfest

### ISSUE THREAD

**Issue by siddhant-khisty** [commclassroom/roadmaps#189]
### Description

As Hacktoberfest is approaching, we want to add the hacktoberfest label to this repository so that PRs will be counted for it. 

Please create a new section in the Readme.MD file which has rules and instructions for contributing during hacktoberfest. Alternatively, you can made a new file called `Hacktoberfest-Readme.md` and link it in the main readme. 

Please mention the following details

- No spam
- PRs for Hacktober will only be considered if an issue was raised beforehand
- Maintain proper code of conduct
- Be polite
- Other general points about Open Source Good Practices.

**Comment by Manice18** [comment]
I can make the required changes can you assign it to me?

**Comment by Manice18** [comment]
![image](https://user-images.githubusercontent.com/91601706/192561751-a1df7efd-2888-4ce7-9be3-5e853cf280f1.png)
I hope this works.

**Comment by Manice18** [comment]
what can I tweak a little can you please elaborate a little ?
like should i add logo of community classroom?

**Comment by Manice18** [comment]
![image](https://user-images.githubusercontent.com/91601706/192575635-d576d6c6-ae14-483b-8efb-2cce64b3199e.png)
does this looks good?

**Comment by siddhant-khisty** [comment]
@Manice18 no no, I don't mean the logo. I meant ways how folks can contribute to this particular repo. By adding learning resources, projects, job portals, doc changes, etc. Basically, everything that is present in this repo. Please also mention that errors on the website will be handled by the internal team but we would still appreciate any bug/improvement reports.

**Comment by Manice18** [comment]
@siddhant-khisty should i take the link of each resource of this repo and paste it?
for eg suppose for backend dev: 
projects(link)
jobs-offers(link)
or should i just write backend dev(link to that repo)

**Comment by siddhant-khisty** [comment]
@Manice18 I don't think that will be necessary, since everything is already well structured.

**Comment by Manice18** [comment]
![image](https://user-images.githubusercontent.com/91601706/192585946-7e2e520f-fe18-4dbe-b623-22c4343e88ab.png)
i already did that  but on addition just added the links.

**Comment by Manice18** [comment]
![image](https://user-images.githubusercontent.com/91601706/192586158-c9051458-aa65-4c04-9417-17b7cf587383.png)

**Comment by Manice18** [comment]
![image](https://user-images.githubusercontent.com/91601706/192586584-5a034d03-499e-4095-9dc2-7dcb08cef922.png)

**Comment by siddhant-khisty** [comment]
@Manice18 This looks good. Please make a PR and link this issue to it

**Comment by Manice18** [comment]
i'll be using the second method which u mentioned so should i first push this hacktoberfest.md ? and then edit the readme.md file?

**Comment by Manice18** [comment]
i think u will have to assign the task to me since i am not able to push it to main branch?

**Comment by Manice18** [comment]
done can u please check
