### ISSUE TITLE
Add resource in Frontend

### ISSUE THREAD

**Issue by sumitkr2000** [commclassroom/roadmaps#197]
### Description

Hey, @kaiwalyakoparkar I want to add resources to the frontend roadmap. Can you assign me this issue? Thank you!

**Comment by siddhant-khisty** [comment]
Hey, the actual roadmap on the website is handled by the internal team for now 

You can link the resource here and we will add it if it is good :slightly_smiling_face:

**Comment by sumitkr2000** [comment]
@siddhant-khisty Can I improve the frontend Lil-bit !?
