### ISSUE TITLE
[FEATURE] Add open source roadmap in the readme format

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [commclassroom/roadmaps#198]
### Description

We need to convert the graphical chart present on [cc roadmaps website] (https://www.commclassroom.org/opensource-roadmap) in the readme format

**Create Readme.md file and add the converted map there**

Eg:

```md
# Open Source

## Introduction
[Resource 1](...)
```

**Comment by tinniaru3005** [comment]
Hey @kaiwalyakoparkar, I want to work on this issue. Can you please assign it to me?

**Comment by Akash190104** [comment]
Hey @kaiwalyakoparkar, I would like to help. Can you please assign this to me?

**Comment by kaiwalyakoparkar** [comment]
@tinniaru3005 sure please go ahead

**Comment by tinniaru3005** [comment]
Hey @kaiwalyakoparkar. Thanks for assigning. Should I name it `readme.md` or `roadmap.md` as In the fullstack roadmap I named it roadmap.md.

**Comment by siddhant-khisty** [comment]
@tinniaru3005 Please keep it `readme.md` as that will get rendered

**Comment by tinniaru3005** [comment]
> @tinniaru3005 Please keep it `readme.md` as that will get rendered

Yes I have done that and sent a PR :)
