### ISSUE TITLE
[FEATURE] Add Frontend roadmap to readme format

### ISSUE THREAD

**Issue by siddhant-khisty** [commclassroom/roadmaps#199]
### Description

Convert the [frontend roadmap on CC website](https://www.commclassroom.org/frontend-roadmap) to a markdown format in the frontend folder. Add it to a file called `roadmap.md`

Example:
```
#Frontend Roadmap
## Step one
- Resource 1
- Resource 2
```

**Comment by vasucp1207** [comment]
Hey, I wanted to work on this issue

**Comment by siddhant-khisty** [comment]
Hey @vasucp1207 feel free to work on it. I've assigned this one, and the frontend one to you

**Comment by vasucp1207** [comment]
Thanks @siddhant-khisty.

**Comment by Purva2803** [comment]
Hey , i am really excited to work on this issue please assign me this.

**Comment by siddhant-khisty** [comment]
Hey @Purva2803, this issue has been fixed. I guess it was not linked to the PR. Feel free to work on one of the other roadmap issues.

**Comment by Purva2803** [comment]
Yes it's not merged, i will work on other issues
.
