### ISSUE TITLE
Rearrange the lists alphabetically

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [commclassroom/roadmaps#2]

**Comment by hasnainmakada-99** [comment]
Hey @kaiwalyakoparkar can please be more specific about the issue, I would like to work on this one

**Comment by kelvinparmar** [comment]
I would like to work on this issue

**Comment by NitanJana** [comment]
> I would like to work on this issue

I've already done the rearranging and opened PR

**Comment by kelvinparmar** [comment]
But still it is display in issue section so that's why I am interested

**Comment by kaiwalyakoparkar** [comment]
@kelvinparmar, @NitanJana has done it for Open Source, if you want you can rearrange for other tech stacks

**Comment by kelvinparmar** [comment]
But what I have to rearrange?

**Comment by kaiwalyakoparkar** [comment]
> But what I have to rearrange?

You can rearrange the project, job boards, and community names alphabetically in the readme of particular tech stack folders

**Comment by kalashjain23** [comment]
I've covered many files (that need to be rearranged) in this PR. Please review my pull request..

**Comment by kaiwalyakoparkar** [comment]
@kalashjain23 I would really appreciate if you comment on the issue before you create a PR. This way others know that this issue is taken.

**Comment by kalashjain23** [comment]
Sorry for this kind of mess!! I'll keep those points in mind from the next time!!

Thank you

**Comment by kaiwalyakoparkar** [comment]
> Sorry for this kind of mess!! I'll keep those points in mind from the next time!!
> 
> Thank you

No worries :D
