### ISSUE TITLE
[FEATURE] Convert the backend roadmap to a readme format

### ISSUE THREAD

**Issue by siddhant-khisty** [commclassroom/roadmaps#200]
### Description

Convert the [backend roadmap on CC website](https://www.commclassroom.org/backend-roadmap to a markdown format in the backend folder. Add it to a file called `roadmap.md`

Example:
```
#Frontend Roadmap
## Step one
- Resource 1
- Resource 2
```

**Comment by vasucp1207** [comment]
Hey, I wanted to work on this issue.

**Comment by vasucp1207** [comment]
Thanks @siddhant-khisty
