### ISSUE TITLE
[FEATURE] Convert Fullstack roadmap to readme format

### ISSUE THREAD

**Issue by siddhant-khisty** [commclassroom/roadmaps#201]
### Description

Convert the [fullstack roadmap on CC website](https://www.commclassroom.org/fullstack-roadmap) to a markdown format in the fullstack folder. Add it to a file called `roadmap.md`

Example:
```
#Frontend Roadmap
## Step one
- Resource 1
- Resource 2
```

**Comment by tinniaru3005** [comment]
Hey @siddhant-khisty . Can you please assign this issue to me. I would like to work on it.
