### ISSUE TITLE
[FEATURE] Convert DevRel roadmap to readme format

### ISSUE THREAD

**Issue by siddhant-khisty** [commclassroom/roadmaps#202]
### Description

Convert the [DevRel roadmap on CC website](https://www.commclassroom.org/devrel-roadmap) to a markdown format in the DevRel folder. Add it to a file called `Readme.md`

Example:
```
#Frontend Roadmap
## Step one
- Resource 1
- Resource 2
```

**Comment by tinniaru3005** [comment]
Hey @siddhant-khisty, I want to work on this issue. Can you please assign it to me?

**Comment by Akash190104** [comment]
Hey @siddhant-khisty, I want to work on this issue. Can you please assign this to me?

**Comment by kaiwalyakoparkar** [comment]
@tinniaru3005 you have been assigned another issue so I will assign this issue to @Akash190104

**Comment by tinniaru3005** [comment]
> @tinniaru3005 you have been assigned another issue so I will assign this issue to @Akash190104

Sure :)
