### ISSUE TITLE
[FEATURE] Convert android roadmap to readme format

### ISSUE THREAD

**Issue by siddhant-khisty** [commclassroom/roadmaps#204]
### Description

Convert the [Android roadmap on CC website](https://www.commclassroom.org/android-roadmap) to a markdown format in the Android folder. Add it to a file called `Readme.md`

Example:
```
#Frontend Roadmap
## Step one
- Resource 1
- Resource 2
```

**Comment by c99SRS** [comment]
HI @siddhant-khisty i can work on this

**Comment by siddhant-khisty** [comment]
this issue was already solved but issue was not linked with PR. Hence closing this issue
