### ISSUE TITLE
[FEATURE] Convert Blockchain roadmap to readme format

### ISSUE THREAD

**Issue by siddhant-khisty** [commclassroom/roadmaps#205]
### Description

Convert the [Blockchain roadmap on CC website](https://www.commclassroom.org/blockchain-roadmap) to a markdown format in the Blockchain folder. Add it to a file called `Readme.md`

Example:
```
#Frontend Roadmap
## Step one
- Resource 1
- Resource 2
```

**Comment by c99SRS** [comment]
Hi @siddhant-khisty can you please assign this to me? I can work on this

**Comment by c99SRS** [comment]
working on it

**Comment by yashdev9274** [comment]
Hey @c99SRS are you working on this issue?

**Comment by siddhant-khisty** [comment]
Hey this issue was already solved but issue was not linked with PR. Hence closing this issue
