### ISSUE TITLE
[Other] Backend Roadmap Suggestion

### ISSUE THREAD

**Issue by vasucp1207** [commclassroom/roadmaps#211]
### Description

- Hey, In the [**Backend roadmap**](https://www.commclassroom.org/backend-roadmap) of **JS Tutorial**  section Resource numbers5 and 7 are same.
- Also why this section is named Javascript why it's not **Nodejs and ExpressJS**?
<img width="791" alt="Screenshot 2022-10-10 at 11 46 31 PM" src="https://user-images.githubusercontent.com/85363195/194929263-5e250a85-c75b-4ac7-97a6-01eb6f3ffd1e.png">

**Comment by siddhant-khisty** [comment]
@vasucp1207 The backend roadmap has been shifted to this GitHub Repo. Feel free to make the changes.

Also, we're referring to it as JavaScript because Node and Express are frameworks based on JS. The core thing to learn is Javascript.

**Comment by kaiwalyakoparkar** [comment]
@vasucp1207 thank you for the issue. You can now create an issue and pr for new format as mentioned by @siddhant-khisty. As the issue you raised is based on older format I will be closing it. Feel free to reach out if you have any questions
