### ISSUE TITLE
Adding 2 new Frontend Projects especially for beginners

### ISSUE THREAD

**Issue by TRohit20** [commclassroom/roadmaps#218]
### Which field of community (DevOps/Opensource/Web/Web3/Android/Devrel) you want to add, drop the links?

Frontend Web Development

### For adding OpenSource Projects, add links here.

1. https://github.com/TRohit20/Soldier-Fit-Factory-Website - A responsive website for a gym.
2. https://github.com/TRohit20/Blogs-Website - A responsive Community Driven Blog website

**Comment by siddhant-khisty** [comment]
Hi @TRohit20 please improve the readme in these two repos. Add instructions on how to build and deploy the project, add a preview for the project etc

**Comment by TRohit20** [comment]
Hey @siddhant-khisty , I have made some changes to the Readme files of both the projects. Please have a look.

**Comment by siddhant-khisty** [comment]
Gym website: You mentioned that this was for a gym you go to. Do you have permission for the gym to distribute the code for this? I would suggest making it a private repo if it is something proprietary.

The blogging website looks good

**Comment by TRohit20** [comment]
No buddy. The gym owner is my close friend and I have discussed this with him. There are no such issues. I can assure you of that. That is why I put it forth for contribution

**Comment by siddhant-khisty** [comment]
@TRohit20 no problems in that case.
