### ISSUE TITLE
https://www.commclassroom.org/roadmaps link not working !

### ISSUE THREAD

**Issue by Mohand2** [commclassroom/roadmaps#219]
### Description

https://www.commclassroom.org/roadmaps link is not working !

### Screenshots

![index](https://user-images.githubusercontent.com/75218777/195907389-65f04aa1-2d39-417c-b4c5-464421f55f7d.png)

**Comment by siddhant-khisty** [comment]
Hi @Mohand2 we have shifted most of the roadmaps to this repository. For the remaining roadmaps we will upload a .svg file that contains the roadmap and will eventually convert it to a markdown format
