### ISSUE TITLE
[FEATURE] Add a index in readme

### ISSUE THREAD

**Issue by siddhant-khisty** [commclassroom/roadmaps#225]
### Description

Add a index in the readme.md which will link to all available roadmaps

**Comment by Ghat0tkach** [comment]
hey @siddhant-khisty , may i get the opportunity to work in this issue?

**Comment by siddhant-khisty** [comment]
@Ghat0tkach sure go for it. Just keep in mind that a few roadmaps have not yet been converted to a markdown format. If I'm not wrong it's the Blockhain, DevOps and Android roadmaps. For these three you can add some text such as `Work in Progress`

**Comment by siddhant-khisty** [comment]
this issue was already solved but issue was not linked with PR. Hence closing this issue
