### ISSUE TITLE
Wrong link in the Roadmap/Resources

### ISSUE THREAD

**Issue by Sreekar-Shodhan** [commclassroom/roadmaps#23]
IN Roadmaps/DevRel , when I click on the "Learning in public and getting opportunities" and on " How to become DevRel " it is showing some other Blog. Detailed in below screenshots.

![image](https://user-images.githubusercontent.com/71596539/182030326-597a6db5-107c-41a8-97d4-8015b99a204c.png)
                    
                   
![image](https://user-images.githubusercontent.com/71596539/182030343-ff4bed67-1669-481f-b3f3-43057febfdbb.png)

![image](https://user-images.githubusercontent.com/71596539/182030370-1802f243-1398-43bb-9e15-6981b9d38671.png)
                      

![image](https://user-images.githubusercontent.com/71596539/182030379-75678217-30f2-4d3a-9a91-076bbcc46e67.png)

**Comment by kaiwalyakoparkar** [comment]
Thanks for reporting @Sreekar-Shodhan. Will be fixed soon

**Comment by kaiwalyakoparkar** [comment]
@Sreekar-Shodhan this has been fixed now, thanks for reporting
