### ISSUE TITLE
Site not found

### ISSUE THREAD

**Issue by souravsk** [commclassroom/roadmaps#232]
### Description

The Roadmaps page is not accessible able it gives a 404 Error.

### Screenshots

![Screenshot from 2022-10-20 18-59-23](https://user-images.githubusercontent.com/33636054/196962064-e1c40799-d0ca-4298-a759-ee95b62df4a4.png)

**Comment by siddhant-khisty** [comment]
@souravsk all the roadmaps have been shifted to this repo. There is no longer a dedicated page for the roadmaps
