### ISSUE TITLE
[FEATURE] Should we add names of the websites instead of just resource 1 but instead resource 1:  Learn HTML free code camp

### ISSUE THREAD

**Issue by Tanmay09516** [commclassroom/roadmaps#236]
### Description

It would not be a big task but would make it all much more accessible, as some of the resources are already consumed by the learners before coming here, so this subtle change would not only make it look pleasant but also improve the user experience.
I would love to work on this and contribute.

**Comment by siddhant-khisty** [comment]
This is a good idea. Feel free to open a PR for the same @Tanmay09516

**Comment by Tanmay09516** [comment]
Okay, I will start the work, thank you for approving!!

**Comment by shivaabhishek07** [comment]
It is a great idea.
I want to work on this issue, Can anyone assign it to me!

**Comment by siddhant-khisty** [comment]
Closing as the PR has been merged
