### ISSUE TITLE
Content out of box

### ISSUE THREAD

**Issue by Sreekar-Shodhan** [commclassroom/roadmaps#24]
Iam using Firefox as my browser and either the content is out of box on every browser or it may be out of box in the firefox browser

**Comment by kaiwalyakoparkar** [comment]
@Sreekar-Shodhan can you please attach some screenshots and check it out on different browsers if possible please? Pretty sure it's a browser bug.

**Comment by AyushPathak3011** [comment]
@kaiwalyakoparkar Facing a similar issue on safari.
Attaching a screenshot for the same.
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/87303184/182040030-0a8f7e10-4227-4e2b-a30c-f1d1ee58c3b5.png">

**Comment by kaiwalyakoparkar** [comment]
@Sreekar-Shodhan @AyushPathak3011 Thank you so much for reporting but there is nothing we can do from our end as it is browser rendering issue. I would suggest you to use chrome or other chrome based browser for same. If we find something that can solve it we will surely implement that :)
