### ISSUE TITLE
[Bug] Blockchain Link was added twice and some roadmap links are broken.

### ISSUE THREAD

**Issue by rwiteshbera** [commclassroom/roadmaps#240]
### Description

1. Blockchain Link was added twice and the wrong link was attached.
2. DevOps Roadmap Link is broken
3. Full Stack Development link is redirecting to Frontend Development Roadmap

Could you please assign me this issue? I want to fix it.

### Screenshots

<img width="523" alt="image" src="https://user-images.githubusercontent.com/73098407/197355658-831542bf-9aa5-4ddb-9bbc-c06c3e6347c1.png">

### Additional information

@siddhant-khisty Hi Siddhant, Could you please assign me this issue?

**Comment by siddhant-khisty** [comment]
Hey @rwiteshbera, there is already a PR open for the mentioned issue
