### ISSUE TITLE
[Bug] Blockchain Resource Link is broken

### ISSUE THREAD

**Issue by J0SAL** [commclassroom/roadmaps#244]
### Description

1. The `Resource 1`  from `Article Format` in the `Project Ideas` section at `https://github.com/commclassroom/roadmaps/tree/main/Blockchain` is pointing to a page that does not exist.

### Screenshots

1. ![image](https://user-images.githubusercontent.com/52382282/197390619-04936702-5107-4467-be26-9165abbdeb1d.png)

**Comment by J0SAL** [comment]
Please assign me this issue, I'll replace the link with the similar one.

**Comment by siddhant-khisty** [comment]
Hey @J0SAL nice catch. Please open a PR and have it point to the blockchain folder

**Comment by siddhant-khisty** [comment]
Closing as issue has been fixed
