### ISSUE TITLE
[FEATURE] Change `Mobile-Development` directory name to `Android-Development`

### ISSUE THREAD

**Issue by inclinedadarsh** [commclassroom/roadmaps#246]
### Description

The `Mobile-Development` directory name can be changed to `Android-Development` because it can be hard for some people to find it.
Also, there will be more consistency in naming as the in the `README.me` file of `Mobile-Development` the header is **Android Development** and it's the same in the `README.md` file of this repo as well.

**Comment by siddhant-khisty** [comment]
Sounds good. Assigned you

**Comment by tcchawla** [comment]
Hello @siddhant-khisty, I've created a PR #255 solving this issue. Please review it and let me know if any changes are required!
