### ISSUE TITLE
[Bug] Blockchain, DevOps & Android-Development Roadmaps Links are broken

### ISSUE THREAD

**Issue by vivaciousvivek** [commclassroom/roadmaps#254]
### Description

`Blockchain`, `DevOps` & `Android-Development` Links in the `Mentorship Roadmaps` section at https://github.com/commclassroom/roadmaps are pointing to a page that does not exist(i.e https://github.com/commclassroom/roadmaps/blob/main).

It should point to:
https://github.com/commclassroom/roadmaps/tree/main/Blockchain#readme
https://github.com/commclassroom/roadmaps/tree/main/DevOps#readme

### Screenshots

<img width="1296" alt="DevOps_Roadmaps_broken_link" src="https://user-images.githubusercontent.com/31936581/197843944-22add8d2-f91f-4ff8-90eb-67a7432b0b3b.png">

### Additional information

Bad URL linking

**Comment by vivaciousvivek** [comment]
Please assign me this issue, I'll replace it with the correct link.

**Comment by vivaciousvivek** [comment]
Apologies clicked on close issue by mistake. 

Please assign this issue to me, I'll replace it with the correct link.

**Comment by Saha-7** [comment]
I am working on it , Please assigned it to me.

**Comment by siddhant-khisty** [comment]
issue has been fixed
