### ISSUE TITLE
[Bug] <description>

### ISSUE THREAD

**Issue by Grangerpriya** [commclassroom/roadmaps#256]
### Description

community link for Frontend Mentor is showing _This link is no longer active_

### Screenshots

![bug](https://user-images.githubusercontent.com/112341946/197954416-1ca26baf-9156-4198-b65c-a7c073130fe8.JPG)

**Comment by Grangerpriya** [comment]
If you can provide me the invite url  of frontend mentor community i am interested in fixing the issue

**Comment by ayushanand308** [comment]
Hey @Grangerpriya are you working on this issue?
