### ISSUE TITLE
[Roadmaps down] <the roadmap link is down>

### ISSUE THREAD

**Issue by MridulTi** [commclassroom/roadmaps#259]
### Description

I have tried to open roadmaps from the community classroom for 2 days now but all the roadmaps pages and even the main roadmap page are showing Error 404  Not found. But then there has been no issue reported regarding it, so I reported this to let the mods know

### Screenshots

Main Roadmap Page
![image](https://user-images.githubusercontent.com/92802892/198493348-4a75ad90-50a8-41ca-8055-17cefff13394.png)
Devrel roadmap page
![image](https://user-images.githubusercontent.com/92802892/198493501-bee37a00-dbd2-4998-96e2-de75c0f3d26e.png)

**Comment by siddhant-khisty** [comment]
All the roadmaps have been shifted to this repo. Readme has been updated to reflect the changes :smile:
