### ISSUE TITLE
[Bug] <Image link in Heading is not working>

### ISSUE THREAD

**Issue by Arindam200** [commclassroom/roadmaps#261]
### Description

In the <code>Hacktoberfest-Readme.md</code> File the Image link  is not working in the Heading **"Community Classroom  Guidelines "**.

### Screenshots

![image](https://user-images.githubusercontent.com/109217591/198567445-876ba60b-0f04-44aa-a9ee-21e5ea412a04.png)

**Comment by tcchawla** [comment]
Hey @kaiwalyakoparkar, I have made a PR, which removes this broken Image from the headline #272. Please let me know if any changes are required. Thanks!
