### ISSUE TITLE
[Bug] <Invalid Link in roadmaps/Open-Source/Communities/>

### ISSUE THREAD

**Issue by SAURABHSINGHDHAMI** [commclassroom/roadmaps#279]
### Description

The cs dojo community link is invalid on the community page of open-source roadmaps - ```roadmaps/Open-Source/Communities/```

```https://github.com/commclassroom/roadmaps/tree/main/Open-Source/Communities```

### Screenshots

![image](https://user-images.githubusercontent.com/95751390/200172231-72464ea4-eaa0-4eaa-942a-980d8750c3c6.png)

### Additional information

the correct link is - ```https://www.csdojo.io/community```

**Comment by siddhant-khisty** [comment]
Fixed by #278
