### ISSUE TITLE
[FEATURE] Add Git and GitHub Tutorial to DevOps Roadmap

### ISSUE THREAD

**Issue by VishwaS-22** [commclassroom/roadmaps#281]
### Description

Hey There! Am opening this Issue to add Git and GitHub tutorial to the DevOps roadmap. As it is necessary to learn but it's not added in the DevOps roadmap. It is available in @kunal-kushwaha's youtube channel. So Please add it to the respective stage. Am very much happy to contribute.

### Screenshots

![Screenshot (146)](https://user-images.githubusercontent.com/85573504/200840252-bb9f9f2c-a527-4e13-ade2-71f39ad6a3d5.png)

### Additional information

I would like to work on this issue. So please assign this to me.

Thankyou!

**Comment by siddhant-khisty** [comment]
Hey @VishwaS-22, the DevOps roadmap is not the appropriate place for the git and GitHub tutorial. It has already been added to the open-source roadmap.

**Comment by VishwaS-22** [comment]
@siddhant-khisty Thanks for the Review! Happy to contribute.
