### ISSUE TITLE
GSOC 2023 ROADMAP

### ISSUE THREAD

**Issue by professorabhay** [commclassroom/roadmaps#287]
### Description

Gsoc 2023 dates announced. So, We can add a road map for gsoc 2023 in the repository. It'll help alot.

### Screenshots

![Screenshot_2022-11-12-15-08-17-341_com android chrome](https://user-images.githubusercontent.com/76243309/201484809-ca31337b-490b-4429-8832-162f9e6e4f5f.png)

**Comment by siddhant-khisty** [comment]
I don't think a GSOC roadmap is appropriate. You get into GSOC based on your experience with building projects, and what value you can add to the projects listed in GSOC. There isn't a roadmap for it as such apart from learning how to build

**Comment by huamanraj** [comment]
yes! there isnt any roadmap for gsoc, you have to just contribute and apply! thats it

**Comment by kaiwalyakoparkar** [comment]
Hey I will be closing this issue with reference to the comment by @siddhant-khisty
