### ISSUE TITLE
The resource link is broken   (BUG)

### ISSUE THREAD

**Issue by nesarptr** [commclassroom/roadmaps#31]
The link of resource no. 2 is broken under the Kubernetes section in the DevOps roadmap.

![Screenshot_1](https://user-images.githubusercontent.com/97525250/182031798-72c4196e-426a-405b-8863-570bf31ee508.png)

![Screenshot_2](https://user-images.githubusercontent.com/97525250/182031884-f98e37d2-3f71-4676-8e61-04f562f877a6.png)

**Comment by kaiwalyakoparkar** [comment]
@nesarptr this link is working on our end, please try following
- Check your internet
- try a different browser
- clear cache and cookies
