### ISSUE TITLE
Spelling mistake in Backend Development Roadmap

### ISSUE THREAD

**Issue by adarsh-gupta101** [commclassroom/roadmaps#34]
There is a spelling mistake in the backend development roadmap at the end 

Nogejs=>NodeJS

![image](https://user-images.githubusercontent.com/73733229/182036435-9ddaed22-95c1-4916-bba5-eee8e9950b4a.png)

**Comment by kelvinparmar** [comment]
I would like to work on this

**Comment by adarsh-gupta101** [comment]
I think this part of the website is not available in this repo

**Comment by kelvinparmar** [comment]
So How can i do this?

**Comment by samjn08** [comment]
Thanks for reporting @adarsh-gupta101. It will be fixed soon!

**Comment by samjn08** [comment]
@adarsh-gupta101 This has been resolved now. Thanks for reporting.

**Comment by samjn08** [comment]
@kelvinparmar, you can check out other issues for contribution
