### ISSUE TITLE
Resource mismatches the name

### ISSUE THREAD

**Issue by AnimeshKumar923** [commclassroom/roadmaps#36]
When clicking the link in:

Roadmaps -> open source -> Learning Git -> **Git documentation**

**Git documentation** opens a video of Eddie Jaoude on FreeCodeCamp's YouTube channel named 'Complete Guide to Open Source'

I suggest to change the resource which links to official documentation of Git.

**Comment by kelvinparmar** [comment]
I would like to work on this

**Comment by samjn08** [comment]
Thanks for reporting @AnimeshKumar923. It will be fixed soon!
