### ISSUE TITLE
Bootstrap link pointing to something else

### ISSUE THREAD

**Issue by amity-ak97** [commclassroom/roadmaps#41]
Bootstrap in CSS Framework in Frontend Development Roadmap links to some job at Apple that doesn't even exist anymore. This issue can be understood more clearly from the video attached.
[screen-capture.webm](https://user-images.githubusercontent.com/54621148/182201157-61a34b93-6430-4e8c-a6df-bb2656d3f1ac.webm)
.

**Comment by amity-ak97** [comment]
Same issue for the 'Tailwind CSS' as well

**Comment by samjn08** [comment]
Thanks for reporting @amity-ak97. It will be fixed soon!

**Comment by samjn08** [comment]
@amity-ak97 This has been resolved now. Thanks for reporting.
