### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by AnimeshKumar923** [commclassroom/roadmaps#42]
When clicking the link in:

Roadmaps -> open source -> Getting Started -> 14 ways to contribute...**genuis**

It should be changed to **genius.**

**Comment by joeshajan** [comment]
I would like to fix this

**Comment by AnimeshKumar923** [comment]
> I would like to fix this

I don't think you can unless you have the source code of the website.

**Comment by kaiwalyakoparkar** [comment]
@AnimeshKumar923 it would be really helpful if you add screenshots etc. It's hard to find the typo with current information provided :)

**Comment by AnimeshKumar923** [comment]
> @AnimeshKumar923 it would be really helpful if you add screenshots etc. It's hard to find the typo with current information provided :)

![Screenshot_2022-08-07-22-52-33-77_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://user-images.githubusercontent.com/99868037/183303215-87ca56ad-7de4-48f6-ac94-352f7e29c8a0.jpg)

This should help...@kaiwalyakoparkar

**Comment by kaiwalyakoparkar** [comment]
@AnimeshKumar923 this has been fixed. thank you so much for raising the issue 🙌
