### ISSUE TITLE
Marking feature in Roadmaps✅

### ISSUE THREAD

**Issue by Pritam0077** [commclassroom/roadmaps#43]
Add marking feature in roadmaps, so that folks could know which part they have completed.

**Comment by cosmicqbit** [comment]
You mean similar to those of roadmap.sh , right?

**Comment by Pritam0077** [comment]
Yeah but might be a good feature if implemented on the website.

**Comment by kaiwalyakoparkar** [comment]
@Pritam0077 that's a great idea but as suggested by @cosmicqbit it's a good idea to log your progress on other software like notion or spreadsheets

**Comment by Pritam0077** [comment]
Yeah👍

**Comment by Pritam0077** [comment]
Yeah👍
