### ISSUE TITLE
Removal of unavailable Jobs 

### ISSUE THREAD

**Issue by priynshuchouhn** [commclassroom/roadmaps#44]
some Job positions are filled or not available at the moment.  update the Readme.md by removing those job roles

**Comment by kaiwalyakoparkar** [comment]
@priynshuchouhn would you like to go ahead with the pr for the same?

**Comment by priynshuchouhn** [comment]
yes. I am working on it. please assign me this task.

**Comment by kaiwalyakoparkar** [comment]
@priynshuchouhn if you have made a pr please make sure to link it to the issue, or if you are currently working on it then you can also create a draft pr for the same :D
