### ISSUE TITLE
Add Reactplay community to contributors and communities as well

### ISSUE THREAD

**Issue by vasantisuthar** [commclassroom/roadmaps#45]
[Reactplay](https://reactplay.io/) is an excellent community for helping folks to get into open source, learn and showwcase their work created by Tapas Adhikary.
Not only is it for frontend but developers can also learn a lot many things about development. I recommend letting more people know about React play to contribute and join the community.

**Comment by kaiwalyakoparkar** [comment]
@vasantisuthar would you like to go ahead and create a pr for this?

**Comment by vasantisuthar** [comment]
Sure
