### ISSUE TITLE
Resource for contributing to open source for beginners.

### ISSUE THREAD

**Issue by sheoranharis** [commclassroom/roadmaps#46]
https://firstcontributions.github.io/ 
this website contains some projects which contain good first issues.

--------------------------------------------------------------------------------------------------------------------
and I have found 2 boot camps in a Reddit discussion for building full stack production ready web apps.
How can I contribute these to Community Classroom,

1. one is for building a full-stack Express app

2. 2nd Bootcamp is by a Professional Software engineer,
he teaches building a full-stack production-grade web app, teaching ruby on rails and relational databases and much more.

**Comment by kaiwalyakoparkar** [comment]
@sheoranharis would you like to go ahead with making a pr for the same?

**Comment by sheoranharis** [comment]
Yes

**Comment by sheoranharis** [comment]
ok, 
but the Fullstack learning resource directory is not there, I am not sure where to put these resources.

**Comment by kaiwalyakoparkar** [comment]
@sheoranharis it's there https://github.com/commclassroom/roadmaps/tree/main/Fullstack-Development/Contribute you can add it here for fullstack

**Comment by kaiwalyakoparkar** [comment]
@sheoranharis seems pr for this issue is merged. Please make sure you link the issue in your pr next time 🙌

**Comment by sheoranharis** [comment]
ok, thank you
