### ISSUE TITLE
Microservice architecture in Backend Roadmap

### ISSUE THREAD

**Issue by harshmittal-cyber** [commclassroom/roadmaps#47]
Please add microservice resources in Backend roadmap. Currently all APIs are built on monolithic architecture in the roadmap

**Comment by kaiwalyakoparkar** [comment]
@harshmittal-cyber thanks for the suggestion. These have been added in the newest revision of of the website :)

**Comment by harshmittal-cyber** [comment]
Thanks @kaiwalyakoparkar .It means a lot for all the folks learning from commclassroom👍
