### ISSUE TITLE
Add more resources.

### ISSUE THREAD

**Issue by enn-dee** [commclassroom/roadmaps#49]
Would appreciate you guys adding resources for Cyber Security/CEH to the roadmap.

**Comment by cosmicqbit** [comment]
Check this out 
https://github.com/gokhangokcen1/cyber-security-roadmap

**Comment by enn-dee** [comment]
Perfect one thanks.

**Comment by kaiwalyakoparkar** [comment]
@enn-dee we are coming up with Cyber security roadmap soon. I am glad that you found out resources for now. Please do add these resource to the discussion #27 where someone has suggested and asked about the same :)
