### ISSUE TITLE
Add more resources 

### ISSUE THREAD

**Issue by Nishchay1571999** [commclassroom/roadmaps#51]
Hi I would really appreciate it if you guys could add AI/ML resources with this also where i as a beginner could contribute to.
Thank you

**Comment by kaiwalyakoparkar** [comment]
@Nishchay1571999 please add it as a suggestion in https://github.com/commclassroom/roadmaps/discussions/27 as we are yet to come up with an AI/ML roadmap. If the project fits in another category of roadmaps that we currently have then please do open a pr accordingly :)
