### ISSUE TITLE
Adding Falso.js in the OSS projects list

### ISSUE THREAD

**Issue by vish-han** [commclassroom/roadmaps#53]
Falso.js is the new alternative of faker.js and it have many good first issues that beginner can contribute too.

**Comment by kaiwalyakoparkar** [comment]
@vish-han sounds good. Would you like to go ahead with the PR?

**Comment by vish-han** [comment]
I will make the PR ASAP

**Comment by kaiwalyakoparkar** [comment]
Hey @vish-han seems like pr for this issue is merged. Please make sure you link the issue to your pr next time 🙌
