### ISSUE TITLE
GSoc all frontend project

### ISSUE THREAD

**Issue by mihir2226** [commclassroom/roadmaps#54]

**Comment by kaiwalyakoparkar** [comment]
@mihir2226 would you please give some context of opening this issue?

**Comment by mihir2226** [comment]
@kaiwalyakoparkar I seen kunals post on linkdin and I also following frontend developer roadmap on community classroom site. I am searching for projects on which I work or learn to work.

**Comment by kaiwalyakoparkar** [comment]
@mihir2226 sorry but I am still not able to understand the purpose of this issue 😓

**Comment by mihir2226** [comment]
@kaiwalyakoparkar he said to come to repo and make PR here. I think I got wrong 😅

**Comment by kaiwalyakoparkar** [comment]
@mihir2226 oh, no problem. You can open a new issue and pr if you want to suggest some open source projects, jobs boards or communities and add them to the current list

**Comment by mihir2226** [comment]
Ohk
