### ISSUE TITLE
Fixing Node js Spelling Inside the Backend Development Website

### ISSUE THREAD

**Issue by PradumTiwari** [commclassroom/roadmaps#58]
hii @kaiwalyakoparkar there is a little spelling mistake inside the backend  development website under the category of build projects by printing the **node.js** spelling as **noge.js**. 

![Screenshot (21)](https://user-images.githubusercontent.com/97210098/183305916-8ac54a17-f3e8-4ea8-aae2-f9f60f664ed5.png)

**Comment by kaiwalyakoparkar** [comment]
@PradumTiwari thank you so much for reporting. It will be fixed soon :)

**Comment by kaiwalyakoparkar** [comment]
@PradumTiwari this is fixed. Thank yo so much for raising the issue 🙌
