### ISSUE TITLE
Add Versatile Data Kit to the opensource project list

### ISSUE THREAD

**Issue by zverulacis** [commclassroom/roadmaps#69]
The [Versatile Data Kit](https://github.com/vmware/versatile-data-kit) project is open for contribution and has good-first-issues. DataOps project for people with basic SQL and Python skills to create data pipelines. Let me know if you feel like it fits, and I can create a PR, thanks!

**Comment by kaiwalyakoparkar** [comment]
@zverulacis sure you can go ahead and create a pr. (Please don't forget to mention/link this issue to the pr)
