### ISSUE TITLE
Add a job board in the Frontend development job boards folder

### ISSUE THREAD

**Issue by Ryukemeister** [commclassroom/roadmaps#77]
Hi, I'd like to add another job board in the /Frontend-Development/Job-Boards folder
- [jobboardsearch.com](https://jobboardsearch.com/entry-level+frontend-jobs-only+remote-jobs?remote_data=true)

Kindly permit to raise a PR. Thanks!

**Comment by kaiwalyakoparkar** [comment]
@Ryukemeister please go ahead and create the pr. Please make sure you mention/link this issue to the pr

**Comment by Ryukemeister** [comment]
Thank you!
