### ISSUE TITLE
I want to add a slack community of go language.

### ISSUE THREAD

**Issue by sheoranharis** [commclassroom/roadmaps#91]
Gophers Slack - https://join.slack.com/t/gophers/shared_invite/zt-1e38v9g5x-lMagjfZcxMlVqX5mL3t3Wg

**Comment by kaiwalyakoparkar** [comment]
@sheoranharis please go ahead and create a pr for this. Please make sure you mention/link this issue to the pr :)

**Comment by siddhant-khisty** [comment]
Stale for more than 30 days
